### ISSUE TITLE
Update to 1.21 broke reopen last closed tabs feature.

### ISSUE THREAD

**Issue by Shahius** [onemen/TabMixPlus#307]
TabMixPlus updated today by itself to 1.21 version. After that Reopen last closed tabs feature stopped working. I was trying to reopen tab but nothing happened.
Rollback to 1.20 helped. 
So, I just turned off updates.

Firefox ESR 115.12.0esr (64-bit)

**Comment by onemen** [comment]
Do you see any messages in the Browser console after you try to open  last closed tabs?

**Comment by Shahius** [comment]
![Screenshot_16](https://github.com/onemen/TabMixPlus/assets/107578713/1a8bbfd5-0b56-4765-a643-d881e6104da5)

This is screenshot of console.
Where is TabMix Plus prefs file? In the profile folder? What file exactly should I attach?

**Comment by onemen** [comment]
Download and install the latest [development buid](https://github.com/onemen/TabMixPlus/releases/download/dev-build/tab_mix_plus-dev-build.xpi)

Report if it solved this issue

**Comment by Shahius** [comment]
Looks like the issue is solved with the devs build. Thank you.

**Comment by Lister0fSmeg** [comment]
The reopening of closed tabs is still broken when using TMP 1.21.1 and Waterfox G5.1.12 because I have updated to 1.21.1 on two Sandboxed browsers, One of which I checked that tab reopening worked before updating then failed to work after the update.

**Comment by onemen** [comment]
@Lister0fSmeg, 

do you see any messages in the Browser console when you try to reopen closed tabs?

**Comment by onemen** [comment]
This issue is stile a problem for Firefox versions before 115 and for Waterfox before G6

I hope to upload new version next week.

You can solved this issue also by updating to the latest version of you browser
