### ISSUE TITLE
Firefox 135 reopen closed tabs don't work

### ISSUE THREAD

**Issue by Morf2015** [onemen/TabMixPlus#391]
In firefox 135 with enabled tabmixplus, "reopen closed tab" context menu don't reopen closed tabs
With tabmixplus disabled this context menu reopened last closed tab properly

Steps  to reproduce
1. Launch firefox with  tabmixplus 1.26.0 installed
2. Open couple tabs
3. Close tab
4. Try reopen closed tab using context menu

![Image](https://github.com/user-attachments/assets/127d92be-7fa7-479f-845a-6f9ac3e551f1)

**Comment by onemen** [comment]
Thank you for the report, I am working on a fix

**Comment by onemen** [comment]
I just pushed another development build this issue.

Download and install latest [development build](https://github.com/onemen/TabMixPlus/releases/tag/dev-build)

**Comment by 117649** [comment]
@onemen 
Still see this on 136.0b2 with 20250205.1837.
The function seem fine.
```
Tabmix:
change_utility was unable to change window.undoCloseTab.
can't find string
    /tab = SessionStore\.undoCloseTab.*\n.*true;/

Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues
[tablib.js:854:7](chrome://tabmixplus/content/minit/tablib.js)
```

**Comment by 117649** [comment]
> [@117649](https://github.com/117649)
> 
> I don't see this
> 
> can you open Firefox browser/omni.ja (it is a zip file) and attach the content of `chrome/browser/content/browser/browser.js` as text file
> 
> try to change line 845 in tab.js to `/tab = SessionStore\.undoCloseTab.*\n[^;]*true;/,`
> 
> also post what the output of `window.undoCloseTab.toString()` in Browser console

Its something on my side. Nothing to worry I'll deal it myself.
